name: Run API Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Start backend server
        run: npm start &

      - name: Wait for server to be ready
        uses: jakejarvis/wait-action@v1
        with:
          url: http://localhost:5173
          timeout: 30

      - name: Run Newman tests
        run: |
          npx newman run postman-collections/mataffaren.collection.json --reporters cli,json --reporter-json-export newman-report.json

      - name: Run Cucumber + Chai tests
        run: npm run test:cucumber
